Description: Setup IAM policies, groups and accounts
AWSTemplateFormatVersion: 2010-09-09
Resources:
  # !! IMPORTANT !! - AWS API will refuse to remove users that have attached resources.
  # Therefore you must do the following before deleting them from this file:
  # 1. Detach or remove the following user resources: login profile, attached
  #    MFA device, access-keys, ssh-keys, and policies.
  # 2. Detach the user from all groups.
  ButlerUser:
    Type: 'AWS::IAM::User'
    Properties:
      Groups:
        - !Ref ReadOnlyUsersGroup
  ReadOnlyUsersGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
Outputs:
  ButlerUserName:
    Value: !Ref ButlerUser
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ButlerUserName'
  ButlerUserArn:
    Value: !GetAtt ButlerUser.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ButlerUserArn'
